const MessageTag = {
  ALL_REQ: 'All fields are required',
  ValidEmail: 'Please enter a valid email',
  WelcomeMsg: 'Welcome to Virtuevise Portal.',
  PasswordWrong: 'Password incorrect.',
  NotFoundEmail: 'User Not Found.',
  EXIST_GTC: 'Category already exists.',
  GTC_NOT: 'Category Not found.',
  GTC_UPDATE: 'Category updated successfully.',
  GTC_ADD: 'Global Type Category Added Successfully.',
  GTC_DELETE: 'Category deleted successfully.',
  GTC_LIST: 'GLobal Type Category List.',
  GLOBALTYPE_ADD: 'Global Type Added Successfully.',
  GLOBALTYPE_NOT_FOUND: 'Global type not found with this category.',
  GLOBALTYPE_EXIST: 'Global type already exists.',
  GLOBALTYPE_NOT_EXIST: 'Global type not found.',
  GLOBALTYPE_DELETE: 'Global type deleted successfully.',
  GLOBALTYPE_UPDATE: 'Global type updated successfully.',
  USER_EXIST: 'User Already exists.',
  USER_NOT_EXIST: 'Employee Not exists.',
  USER_ADDED: 'User Added Successfully.',
  ERROR_OCCURRED: 'Some error occurred while creating record.',
  CONTENT_NOT_FOUND: 'Content can not be empty.',
  LEAVE_EXIST: 'Leave already applied for this date.',
  LEAVE_MARK: 'Leave Marked.',
  LEAVE_UPDATED: 'Leave Updated.',
  EVENT_EXIST: 'Event already added for this date.',
  EVENT_MARKED: 'Event Added.',
  EVENT_UPDATED: 'Event Updated.',
  EMAIL_EXISTS: 'Email already exists.',
  EMPLOYEE_ID_EXISTS: 'Employee ID already exists.',
  ATTENDANCE_NOT_FOUND: "Data doesn't exist.",
  INVALID_TOKEN: 'Invalid token.',
  USER_NOT_FOUND: 'User does not exist.',
  ALREADY_TAKEN: 'This Business Name is already taken.',
  CLIENT_ADDED: 'Client Information added successfully',
  CLIENT_UPDATED: 'Client Information updated successfully',
  PROJECT_INFO_ADDED: 'Project Information added successfully',
  PROJECT_INFO_UPDATED: 'Project Information updated successfully',
  PROJECT_ASSIGNED: 'Assigned Successfully',
  DOCUMENT_NOT_FOUND: 'Document not found',
  SALARY_SLIP_FOUND: 'Salary Slip not found',
  LEAVE_REQUEST_NOT_FOUND: 'Leave Request not found!',
  LEAVE_REQUEST_DELETED: 'Leave Request Deleted!',
  DOWN_TIME_EXIST: 'Down time already marked for today',
  EXCEPTION_EXIST: 'This type of exception already exists for this date',
  DOWN_TIME_NOT_EXIST: 'Down time not exist!',
  CONCERN_NOT_EXIST: 'Concern Person Not Assigned To Department',
  DOWN_TIME_MARKED: 'Down Time Marked!',
  DOWN_TIME_DELETED: 'Down Time Deleted!',
  RYG_UPDATED: 'RYG Status Updated!',
  PERMISSION_UPDATED: 'Module Permission Updated!',
  ROLE_CREATED_UPDATED: 'Record created/updated successfully!',
  SUCCESS: 'Success',
  NO_RECORD: 'No record found',
  TRAINEE_NOT_FOUND: 'Trainee Not Found',
  APPLY_TIME_OVER: 'APPLY_TIME_OVER',
  LEAVE_TYPE_LEAVE_COUNT: 'Leave count is fetch for leave types',
  TEAM_PENDING_LEAVE: 'Team Pending leave fetched',
  DEVELOPER_NOT_EXIST: 'Developer not exists' 
}
const StatusEnums = {
  APPROVED: 1,
  REJECTED: 2,
  PENDING: 0,
}

const BooleanEnums = {
  YES: 1,
  NO: 0,
}

const UserRole = {
  EMPLOYEE: 2,
  ADMIN: 4,
  SUPER_ADMIN: 28,
  USER: 29,
  MANAGER: 107,
  PO: 108,
  HR: 134,
  IT: 136,
  TRAINER: 138,
  QUALITY: 140,
  TL: 142,
  TRAINEE: 144,
  ASSISTANT_MANAGER: 176,
}
const ExceptionRequest = {
  BIOMETRIC_ISSUE: 167,
}
module.exports = {
  UserRole,
  MessageTag,
  StatusEnums,
  BooleanEnums,
  ExceptionRequest,
}
